name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t hikshithasiddharth/accuknox:wc .
        # Replace <registry>, <image_name>, and <tag> with your Docker registry details

      - name: Push Docker image
        run: docker push hikshithasiddharth/accuknox:wc
        # Replace <registry>, <image_name>, and <tag> with your Docker registry details

